# Copyright Statement:
#
#

.PHONY: all

RELATIVE_PATH := ../../../../..
TARGET_PATH := project/mt2523_hdk/apps/headset_ref_design/GCC
FEATURE := feature_inear.mk
PROJ_NAME := inear_noodles_headset_ref_design

all:
	@+make -C $(strip $(RELATIVE_PATH))/$(TARGET_PATH) TARGET_PATH=$(TARGET_PATH) FEATURE=$(FEATURE) PROJ_NAME=$(PROJ_NAME)

